# Site settings
name: mpp
title: Molecular Programming Project
email: shawn.douglas@ucsf.edu
description: "Molecular Programming | Architectures, Abstractions, Algorithyms and Applications"
baseurl: ""
url: "http://bionano.io"

# Build settings
markdown: kramdown
permalinks: pretty

#opengraph stuff
og_image: assets/images/icon-300x300.jpg # Default image for Open Graph tag
og_image_type: image/jpg
og_image_width: 300
og_image_height: 300
#fb_profile_id: cooltrainer.org
#fb_admins: 000000

# pagination
paginate: 5
paginate_path: "publications/page:num/index.html"

# Sass settings
sass:
    sass_dir: assets/_sass
    style: :compressed
