# Site settings
name: MPP
title: Molecular Programming Project
email: your-email@domain.com
description: "Molecular Programming | Architectures, Abstractions, Algorithyms and Applications"
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalinks: pretty

# pagination
paginate: 5
paginate_path: "news/page:num/index.html"

# Sass settings
sass:
    sass_dir: assets/_sass
    style: :compressed
